name: architecture_template
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Core Dependencies
  kartal: ^3.5.0
  vexana: ^3.5.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.5
  json_annotation: ^4.8.1
  envied: ^0.3.0+3
  easy_localization: ^3.0.3

  # dependency_overrides:
  #   cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/
